# Development Ingress Configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bots-edi-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: traefik
  rules:
    - host: bots-edi-dev.pminc.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bots-webserver-dev
                port:
                  number: 8080
  tls:
    - hosts:
        - bots-edi-dev.pminc.me
      secretName: bots-edi-dev-tls
