apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edi

resources: 
  - ../../base



configMapGenerator:
- files:
  - config/bots.ini
  name: bots-config-ini
- files:
  - config/settings.py
  name: bots-config-settings