apiVersion: v1
kind: Secret
metadata:
  name: bots-minio-helper-secret
type: Opaque
stringData:
  MINIO_ENDPOINT: "http://minio:9000"
  MINIO_ACCESS_KEY: "minio-access-key"
  MINIO_SECRET_KEY: "minio-secret-key"
  MINIO_REGION: "us-east-1"
  MINIO_BUCKET: "edi"
