---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bots-edi-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - secretName: bots-edi-tls
      hosts:
        - edi.k8.pminc.me
  rules:
    - host: edi.k8.pminc.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bots-webserver
                port:
                  name: http
