apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edi-dev

resources:
- ../../base


configMapGenerator:
- files:
  - config/bots.ini
  name: bots-config-ini
- files:
  - config/settings.py
  name: bots-config-settings
patches:
- path: ingress1-patch.yaml
- path: ingress2-patch.yaml
- path: env-patch.yaml
- path: cert-patch.yaml
